### ISSUE TITLE
Wrong margin value in notebookstyle.css file

### ISSUE THREAD

**Issue by Oedipsos** [aquaULB/solving_pde_mooc#10]
When running the last cell of a notebook, which is loading the CSS file for the notebook layout, I get a left-margin tha's exceeding the size of the notebook container, like on this image 
![Screenshot from 2020-10-01 14-35-37](https://user-images.githubusercontent.com/34401795/94809797-69174100-03f3-11eb-83f8-b421a70ec386.png)

How? Using the "restart the kernel, then re-run the whole notebook (with dialog)" button, and waiting for the whole notebook to be executed

System: Fedora 31, Kernel 5.8.11-100

**Comment by bknaepen** [comment]
Another student reported this; it seems to be related to the full screen mode. If you leave the browser in regular mode, you should not see the issue. Correct?

**Comment by Oedipsos** [comment]
Setting the `margin-left` attribute of the `notebook-container` div to `auto seems to be solving the problem, so setting this attribute in the notebookstyle.css file might be useful

(Answer to your reply: I'm not in full screen, i just cropped the image to the actual display size)
![Screenshot from 2020-10-01 14-38-52](https://user-images.githubusercontent.com/34401795/94810493-5d784a00-03f4-11eb-8aa1-690bc86892f4.png)

**Comment by bknaepen** [comment]
Ok we will look into that...

**Comment by Oedipsos** [comment]
In the `/notebook/styles/notebook.css` file changing this:

```css
div #notebook { /* centre the content */
    background: #fff; /* white background for content */
    width: 1200px; /* --- Change to auto --- /*
    margin: auto;
    padding-left: 0em;
}
```
Does "solve the problem"
